server:
  port: 8082

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: Lakshmi11@B
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

kafka:
  consumer:
    bootstrap-servers: localhost:9092
    group-id: inventory-group
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"
